// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transaction.proto

package proto.schema;

public final class TransactionProto {
  private TransactionProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TransactionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.schema.Transaction)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string atm_machine_id = 1;</code>
     * @return Whether the atmMachineId field is set.
     */
    boolean hasAtmMachineId();
    /**
     * <code>required string atm_machine_id = 1;</code>
     * @return The atmMachineId.
     */
    java.lang.String getAtmMachineId();
    /**
     * <code>required string atm_machine_id = 1;</code>
     * @return The bytes for atmMachineId.
     */
    com.google.protobuf.ByteString
        getAtmMachineIdBytes();

    /**
     * <code>required string customer_id = 2;</code>
     * @return Whether the customerId field is set.
     */
    boolean hasCustomerId();
    /**
     * <code>required string customer_id = 2;</code>
     * @return The customerId.
     */
    java.lang.String getCustomerId();
    /**
     * <code>required string customer_id = 2;</code>
     * @return The bytes for customerId.
     */
    com.google.protobuf.ByteString
        getCustomerIdBytes();

    /**
     * <code>required double amount = 3;</code>
     * @return Whether the amount field is set.
     */
    boolean hasAmount();
    /**
     * <code>required double amount = 3;</code>
     * @return The amount.
     */
    double getAmount();

    /**
     * <code>required .google.protobuf.Timestamp event_timestamp = 4;</code>
     * @return Whether the eventTimestamp field is set.
     */
    boolean hasEventTimestamp();
    /**
     * <code>required .google.protobuf.Timestamp event_timestamp = 4;</code>
     * @return The eventTimestamp.
     */
    com.google.protobuf.Timestamp getEventTimestamp();
    /**
     * <code>required .google.protobuf.Timestamp event_timestamp = 4;</code>
     */
    com.google.protobuf.TimestampOrBuilder getEventTimestampOrBuilder();
  }
  /**
   * Protobuf type {@code proto.schema.Transaction}
   */
  public static final class Transaction extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.schema.Transaction)
      TransactionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Transaction.newBuilder() to construct.
    private Transaction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Transaction() {
      atmMachineId_ = "";
      customerId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Transaction();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Transaction(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              atmMachineId_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              customerId_ = bs;
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              amount_ = input.readDouble();
              break;
            }
            case 34: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) != 0)) {
                subBuilder = eventTimestamp_.toBuilder();
              }
              eventTimestamp_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(eventTimestamp_);
                eventTimestamp_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.schema.TransactionProto.internal_static_proto_schema_Transaction_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.schema.TransactionProto.internal_static_proto_schema_Transaction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.schema.TransactionProto.Transaction.class, proto.schema.TransactionProto.Transaction.Builder.class);
    }

    private int bitField0_;
    public static final int ATM_MACHINE_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object atmMachineId_;
    /**
     * <code>required string atm_machine_id = 1;</code>
     * @return Whether the atmMachineId field is set.
     */
    @java.lang.Override
    public boolean hasAtmMachineId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string atm_machine_id = 1;</code>
     * @return The atmMachineId.
     */
    @java.lang.Override
    public java.lang.String getAtmMachineId() {
      java.lang.Object ref = atmMachineId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          atmMachineId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string atm_machine_id = 1;</code>
     * @return The bytes for atmMachineId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAtmMachineIdBytes() {
      java.lang.Object ref = atmMachineId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        atmMachineId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CUSTOMER_ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object customerId_;
    /**
     * <code>required string customer_id = 2;</code>
     * @return Whether the customerId field is set.
     */
    @java.lang.Override
    public boolean hasCustomerId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string customer_id = 2;</code>
     * @return The customerId.
     */
    @java.lang.Override
    public java.lang.String getCustomerId() {
      java.lang.Object ref = customerId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          customerId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string customer_id = 2;</code>
     * @return The bytes for customerId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCustomerIdBytes() {
      java.lang.Object ref = customerId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        customerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AMOUNT_FIELD_NUMBER = 3;
    private double amount_;
    /**
     * <code>required double amount = 3;</code>
     * @return Whether the amount field is set.
     */
    @java.lang.Override
    public boolean hasAmount() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required double amount = 3;</code>
     * @return The amount.
     */
    @java.lang.Override
    public double getAmount() {
      return amount_;
    }

    public static final int EVENT_TIMESTAMP_FIELD_NUMBER = 4;
    private com.google.protobuf.Timestamp eventTimestamp_;
    /**
     * <code>required .google.protobuf.Timestamp event_timestamp = 4;</code>
     * @return Whether the eventTimestamp field is set.
     */
    @java.lang.Override
    public boolean hasEventTimestamp() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required .google.protobuf.Timestamp event_timestamp = 4;</code>
     * @return The eventTimestamp.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getEventTimestamp() {
      return eventTimestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : eventTimestamp_;
    }
    /**
     * <code>required .google.protobuf.Timestamp event_timestamp = 4;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getEventTimestampOrBuilder() {
      return eventTimestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : eventTimestamp_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasAtmMachineId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCustomerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAmount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEventTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, atmMachineId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, customerId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeDouble(3, amount_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeMessage(4, getEventTimestamp());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, atmMachineId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, customerId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, amount_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getEventTimestamp());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.schema.TransactionProto.Transaction)) {
        return super.equals(obj);
      }
      proto.schema.TransactionProto.Transaction other = (proto.schema.TransactionProto.Transaction) obj;

      if (hasAtmMachineId() != other.hasAtmMachineId()) return false;
      if (hasAtmMachineId()) {
        if (!getAtmMachineId()
            .equals(other.getAtmMachineId())) return false;
      }
      if (hasCustomerId() != other.hasCustomerId()) return false;
      if (hasCustomerId()) {
        if (!getCustomerId()
            .equals(other.getCustomerId())) return false;
      }
      if (hasAmount() != other.hasAmount()) return false;
      if (hasAmount()) {
        if (java.lang.Double.doubleToLongBits(getAmount())
            != java.lang.Double.doubleToLongBits(
                other.getAmount())) return false;
      }
      if (hasEventTimestamp() != other.hasEventTimestamp()) return false;
      if (hasEventTimestamp()) {
        if (!getEventTimestamp()
            .equals(other.getEventTimestamp())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAtmMachineId()) {
        hash = (37 * hash) + ATM_MACHINE_ID_FIELD_NUMBER;
        hash = (53 * hash) + getAtmMachineId().hashCode();
      }
      if (hasCustomerId()) {
        hash = (37 * hash) + CUSTOMER_ID_FIELD_NUMBER;
        hash = (53 * hash) + getCustomerId().hashCode();
      }
      if (hasAmount()) {
        hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getAmount()));
      }
      if (hasEventTimestamp()) {
        hash = (37 * hash) + EVENT_TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getEventTimestamp().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.schema.TransactionProto.Transaction parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.schema.TransactionProto.Transaction parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.schema.TransactionProto.Transaction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.schema.TransactionProto.Transaction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.schema.TransactionProto.Transaction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.schema.TransactionProto.Transaction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.schema.TransactionProto.Transaction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.schema.TransactionProto.Transaction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.schema.TransactionProto.Transaction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.schema.TransactionProto.Transaction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.schema.TransactionProto.Transaction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.schema.TransactionProto.Transaction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.schema.TransactionProto.Transaction prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.schema.Transaction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.schema.Transaction)
        proto.schema.TransactionProto.TransactionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.schema.TransactionProto.internal_static_proto_schema_Transaction_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.schema.TransactionProto.internal_static_proto_schema_Transaction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.schema.TransactionProto.Transaction.class, proto.schema.TransactionProto.Transaction.Builder.class);
      }

      // Construct using proto.schema.TransactionProto.Transaction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getEventTimestampFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        atmMachineId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        customerId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        amount_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (eventTimestampBuilder_ == null) {
          eventTimestamp_ = null;
        } else {
          eventTimestampBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.schema.TransactionProto.internal_static_proto_schema_Transaction_descriptor;
      }

      @java.lang.Override
      public proto.schema.TransactionProto.Transaction getDefaultInstanceForType() {
        return proto.schema.TransactionProto.Transaction.getDefaultInstance();
      }

      @java.lang.Override
      public proto.schema.TransactionProto.Transaction build() {
        proto.schema.TransactionProto.Transaction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.schema.TransactionProto.Transaction buildPartial() {
        proto.schema.TransactionProto.Transaction result = new proto.schema.TransactionProto.Transaction(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.atmMachineId_ = atmMachineId_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.customerId_ = customerId_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.amount_ = amount_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          if (eventTimestampBuilder_ == null) {
            result.eventTimestamp_ = eventTimestamp_;
          } else {
            result.eventTimestamp_ = eventTimestampBuilder_.build();
          }
          to_bitField0_ |= 0x00000008;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.schema.TransactionProto.Transaction) {
          return mergeFrom((proto.schema.TransactionProto.Transaction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.schema.TransactionProto.Transaction other) {
        if (other == proto.schema.TransactionProto.Transaction.getDefaultInstance()) return this;
        if (other.hasAtmMachineId()) {
          bitField0_ |= 0x00000001;
          atmMachineId_ = other.atmMachineId_;
          onChanged();
        }
        if (other.hasCustomerId()) {
          bitField0_ |= 0x00000002;
          customerId_ = other.customerId_;
          onChanged();
        }
        if (other.hasAmount()) {
          setAmount(other.getAmount());
        }
        if (other.hasEventTimestamp()) {
          mergeEventTimestamp(other.getEventTimestamp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasAtmMachineId()) {
          return false;
        }
        if (!hasCustomerId()) {
          return false;
        }
        if (!hasAmount()) {
          return false;
        }
        if (!hasEventTimestamp()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.schema.TransactionProto.Transaction parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.schema.TransactionProto.Transaction) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object atmMachineId_ = "";
      /**
       * <code>required string atm_machine_id = 1;</code>
       * @return Whether the atmMachineId field is set.
       */
      public boolean hasAtmMachineId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string atm_machine_id = 1;</code>
       * @return The atmMachineId.
       */
      public java.lang.String getAtmMachineId() {
        java.lang.Object ref = atmMachineId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            atmMachineId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string atm_machine_id = 1;</code>
       * @return The bytes for atmMachineId.
       */
      public com.google.protobuf.ByteString
          getAtmMachineIdBytes() {
        java.lang.Object ref = atmMachineId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          atmMachineId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string atm_machine_id = 1;</code>
       * @param value The atmMachineId to set.
       * @return This builder for chaining.
       */
      public Builder setAtmMachineId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        atmMachineId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string atm_machine_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAtmMachineId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        atmMachineId_ = getDefaultInstance().getAtmMachineId();
        onChanged();
        return this;
      }
      /**
       * <code>required string atm_machine_id = 1;</code>
       * @param value The bytes for atmMachineId to set.
       * @return This builder for chaining.
       */
      public Builder setAtmMachineIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        atmMachineId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object customerId_ = "";
      /**
       * <code>required string customer_id = 2;</code>
       * @return Whether the customerId field is set.
       */
      public boolean hasCustomerId() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required string customer_id = 2;</code>
       * @return The customerId.
       */
      public java.lang.String getCustomerId() {
        java.lang.Object ref = customerId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            customerId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string customer_id = 2;</code>
       * @return The bytes for customerId.
       */
      public com.google.protobuf.ByteString
          getCustomerIdBytes() {
        java.lang.Object ref = customerId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          customerId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string customer_id = 2;</code>
       * @param value The customerId to set.
       * @return This builder for chaining.
       */
      public Builder setCustomerId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        customerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string customer_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCustomerId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        customerId_ = getDefaultInstance().getCustomerId();
        onChanged();
        return this;
      }
      /**
       * <code>required string customer_id = 2;</code>
       * @param value The bytes for customerId to set.
       * @return This builder for chaining.
       */
      public Builder setCustomerIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        customerId_ = value;
        onChanged();
        return this;
      }

      private double amount_ ;
      /**
       * <code>required double amount = 3;</code>
       * @return Whether the amount field is set.
       */
      @java.lang.Override
      public boolean hasAmount() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required double amount = 3;</code>
       * @return The amount.
       */
      @java.lang.Override
      public double getAmount() {
        return amount_;
      }
      /**
       * <code>required double amount = 3;</code>
       * @param value The amount to set.
       * @return This builder for chaining.
       */
      public Builder setAmount(double value) {
        bitField0_ |= 0x00000004;
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double amount = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAmount() {
        bitField0_ = (bitField0_ & ~0x00000004);
        amount_ = 0D;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp eventTimestamp_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> eventTimestampBuilder_;
      /**
       * <code>required .google.protobuf.Timestamp event_timestamp = 4;</code>
       * @return Whether the eventTimestamp field is set.
       */
      public boolean hasEventTimestamp() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required .google.protobuf.Timestamp event_timestamp = 4;</code>
       * @return The eventTimestamp.
       */
      public com.google.protobuf.Timestamp getEventTimestamp() {
        if (eventTimestampBuilder_ == null) {
          return eventTimestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : eventTimestamp_;
        } else {
          return eventTimestampBuilder_.getMessage();
        }
      }
      /**
       * <code>required .google.protobuf.Timestamp event_timestamp = 4;</code>
       */
      public Builder setEventTimestamp(com.google.protobuf.Timestamp value) {
        if (eventTimestampBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          eventTimestamp_ = value;
          onChanged();
        } else {
          eventTimestampBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>required .google.protobuf.Timestamp event_timestamp = 4;</code>
       */
      public Builder setEventTimestamp(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (eventTimestampBuilder_ == null) {
          eventTimestamp_ = builderForValue.build();
          onChanged();
        } else {
          eventTimestampBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>required .google.protobuf.Timestamp event_timestamp = 4;</code>
       */
      public Builder mergeEventTimestamp(com.google.protobuf.Timestamp value) {
        if (eventTimestampBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0) &&
              eventTimestamp_ != null &&
              eventTimestamp_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            eventTimestamp_ =
              com.google.protobuf.Timestamp.newBuilder(eventTimestamp_).mergeFrom(value).buildPartial();
          } else {
            eventTimestamp_ = value;
          }
          onChanged();
        } else {
          eventTimestampBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>required .google.protobuf.Timestamp event_timestamp = 4;</code>
       */
      public Builder clearEventTimestamp() {
        if (eventTimestampBuilder_ == null) {
          eventTimestamp_ = null;
          onChanged();
        } else {
          eventTimestampBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>required .google.protobuf.Timestamp event_timestamp = 4;</code>
       */
      public com.google.protobuf.Timestamp.Builder getEventTimestampBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getEventTimestampFieldBuilder().getBuilder();
      }
      /**
       * <code>required .google.protobuf.Timestamp event_timestamp = 4;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getEventTimestampOrBuilder() {
        if (eventTimestampBuilder_ != null) {
          return eventTimestampBuilder_.getMessageOrBuilder();
        } else {
          return eventTimestamp_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : eventTimestamp_;
        }
      }
      /**
       * <code>required .google.protobuf.Timestamp event_timestamp = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getEventTimestampFieldBuilder() {
        if (eventTimestampBuilder_ == null) {
          eventTimestampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getEventTimestamp(),
                  getParentForChildren(),
                  isClean());
          eventTimestamp_ = null;
        }
        return eventTimestampBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.schema.Transaction)
    }

    // @@protoc_insertion_point(class_scope:proto.schema.Transaction)
    private static final proto.schema.TransactionProto.Transaction DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.schema.TransactionProto.Transaction();
    }

    public static proto.schema.TransactionProto.Transaction getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Transaction>
        PARSER = new com.google.protobuf.AbstractParser<Transaction>() {
      @java.lang.Override
      public Transaction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Transaction(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Transaction> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Transaction> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.schema.TransactionProto.Transaction getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_schema_Transaction_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_schema_Transaction_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021transaction.proto\022\014proto.schema\032\037googl" +
      "e/protobuf/timestamp.proto\"\177\n\013Transactio" +
      "n\022\026\n\016atm_machine_id\030\001 \002(\t\022\023\n\013customer_id" +
      "\030\002 \002(\t\022\016\n\006amount\030\003 \002(\001\0223\n\017event_timestam" +
      "p\030\004 \002(\0132\032.google.protobuf.TimestampB \n\014p" +
      "roto.schemaB\020TransactionProto"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_proto_schema_Transaction_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_schema_Transaction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_schema_Transaction_descriptor,
        new java.lang.String[] { "AtmMachineId", "CustomerId", "Amount", "EventTimestamp", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
